Feature/#30
msperkow/proc_gen_opengl pull request #61
Opened 2020-10-25 17:36 UTC by szymonzygzula

2020-10-26 11:40 UTC, msperkow requested changes
Great work, only a minute change to colorer member field

2020-10-26 11:40 UTC, msperkow commented on include/controller/terrain_translator.hpp
> +	TerrainColorer* colorer;
Please change this to a normal variable, not of pointer type

2020-10-26 11:40 UTC, msperkow commented on src/controller/terrain_translator.cpp
> +	colorer = new TerrainColorer();
Please remove this once colorer is changed to normal variable

2020-10-27 21:23 UTC, szymonzygzula commented
Mistaked has been corrected

2020-10-28 07:29 UTC, msperkow approved these changes
All clear, go ahead and merge

2020-10-28 09:45 UTC, merged